name: CI workflow
on: push

env:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup cache
      uses: actions/cache@v1
      with:
        path: .m2/repository/
        key: ${{ github.ref }}
    - name: Install dependencies
      id: install
      run: mvn $MVN_CLI_OPTS clean install

    


